import type { FaqItem } from "./seo";

// Disalin 1:1 dari xssr@ec66035 index.html (jawaban = HTML, render via dangerouslySetInnerHTML).
export const FAQ_HOME: FaqItem[] = [
  { q: 'Apa itu XL SATU?', a: 'XL SATU adalah layanan internet rumah unlimited terbaik, hasil integrasi XL Home dan First Media. Menggunakan jaringan fiber optik XLSMART yang cepat dan stabil untuk seluruh keluarga.' },
  { q: 'Apakah merger antara XL dan Smartfren akan berdampak pada pelanggan atau layanan XL SATU?', a: 'Merger XL dan Smartfren tidak berdampak negatif pada layanan XL SATU. Justru dengan bergabungnya kedua jaringan, kualitas dan jangkauan layanan akan semakin meningkat untuk pelanggan.' },
  { q: 'Siapa saja yang dapat berlangganan XL SATU?', a: 'Siapa pun yang berada di area layanan XL SATU dapat berlangganan. Cukup hubungi sales kami untuk mengecek ketersediaan di area Anda.' },
  { q: 'Apa saja yang dapat mempengaruhi kecepatan internet XL SATU?', a: 'Faktor yang mempengaruhi kecepatan antara lain: jumlah perangkat yang terhubung, jarak dari router, interferensi sinyal, dan kondisi jaringan saat jam sibuk. Baca <a href="https://xlsatusolo.com/penyebab-wifi-lemot-cara-mengatasi/">panduan lengkap penyebab dan cara mengatasi WiFi lemot</a> untuk tips lebih detail.' },
  { q: 'Apa arti dari First Media Jadi XL SATU?', a: 'First Media resmi bergabung dengan XL Home menjadi satu layanan bernama XL SATU. Pelanggan lama First Media akan secara otomatis beralih ke layanan XL SATU dengan kualitas yang lebih baik.' },
  { q: 'Apakah XL SATU tersedia di Solo dan sekitarnya?', a: 'Ya! XL SATU tersedia di wilayah Solo Raya meliputi Kota Solo, Sukoharjo, Karanganyar, Klaten, dan Boyolali. Hubungi sales kami untuk mengecek ketersediaan di alamat spesifik Anda.' },
  { q: 'Apakah ada toko atau kantor XL SATU / XL Center di Solo untuk pasang WiFi langsung?', a: 'Pendaftaran XL SATU di wilayah Solo Raya tidak perlu datang ke toko atau XL Center — semua proses bisa dilakukan langsung via WhatsApp ke sales resmi kami di 0877-7899-9141. Cukup kirim nama, alamat lengkap, dan paket yang diinginkan, lalu tim kami akan mengatur jadwal survei dan instalasi langsung ke lokasi Anda tanpa perlu antre ke kantor.' },
  { q: 'Berapa lama proses pemasangan internet di Solo Raya?', a: 'Proses instalasi biasanya memakan waktu 3–7 hari kerja setelah pendaftaran. Tim teknisi kami akan menghubungi Anda untuk mengatur jadwal pemasangan yang sesuai. Untuk wilayah Solo Kota biasanya lebih cepat.' },
  { q: 'Apa perbedaan paket Fiber dan Wireless XL SATU?', a: 'Paket Fiber menggunakan kabel fiber optik langsung ke rumah — koneksi paling stabil dan cepat, ideal untuk area yang sudah terjangkau jaringan FTTH. Paket Wireless menggunakan sinyal radio tanpa kabel — solusi untuk area yang belum terjangkau kabel fiber, dengan sistem bayar 3 bulan dan gratis 1 bulan. Baca <a href="https://xlsatusolo.com/panduan-fiber-vs-wireless/">panduan lengkap memilih fiber atau wireless</a> untuk penjelasan lebih detail.' },
  { q: 'Bagaimana cara daftar XL SATU di Solo Raya?', a: 'Pendaftaran bisa langsung melalui WhatsApp sales kami di 0877-7899-9141. Cukup kirim nama, alamat lengkap, dan paket yang diinginkan. Tim kami akan memproses dan mengatur jadwal survei serta instalasi. Baca <a href="https://xlsatusolo.com/cara-daftar-pasang-wifi-xl-satu-solo/">panduan lengkap cara daftar & syarat pemasangan</a> untuk detail langkah demi langkah, lihat juga <a href="https://xlsatusolo.com/biaya-pasang-wifi-solo-raya/">rincian lengkap biaya pasang WiFi</a> sebelum mendaftar, atau baca <a href="https://xlsatusolo.com/internet-rakyat-vs-xl-satu/">perbandingan dengan Internet Rakyat</a> kalau masih bandingkan pilihan.' },
  { q: 'Siapa sales resmi XL SATU untuk Solo Raya?', a: 'Sales resmi XL SATU Solo Raya bisa dihubungi langsung via WhatsApp di 0877-7899-9141. Kami melayani pemasangan fiber optic dan wireless di 5 wilayah Solo Raya: Kota Solo, Sukoharjo, Karanganyar, Klaten, dan Boyolali, dengan proses konsultasi paket, cek ketersediaan jaringan, hingga jadwal instalasi langsung ditangani tim kami tanpa perlu antre ke kantor.' },
  { q: 'Berapa nomor WhatsApp sales resmi XL SATU Solo Raya?', a: 'Nomor WhatsApp sales resmi XL SATU Solo Raya adalah 0877-7899-9141. Chat langsung untuk konsultasi paket, cek jangkauan jaringan di alamat Anda, dan proses pendaftaran — tersedia untuk area Solo, Sukoharjo, Karanganyar, Klaten, dan Boyolali.' },
  { q: 'Apakah ada kontrak berlangganan minimum?', a: 'Untuk paket Fiber, terdapat minimal berlangganan sesuai ketentuan yang berlaku. Untuk paket Wireless, sistem pembayaran adalah per 3 bulan dengan bonus 1 bulan gratis. Hubungi sales kami untuk informasi kontrak terbaru.' },
  { q: 'Apakah harga sudah termasuk router WiFi?', a: 'Ya, paket XL SATU sudah termasuk perangkat router WiFi yang disediakan. Router dikelola oleh XL SATU dan akan dirawat/diganti jika ada kerusakan yang bukan disebabkan oleh pengguna.' },
  { q: 'Apa itu Speed Booster? Apakah kecepatannya permanen?', a: 'Speed Booster adalah bonus kecepatan di atas paket dasar, khusus paket 250 Mbps (normal 100 Mbps), 300 Mbps (normal 200 Mbps), dan 400 Mbps (normal 300 Mbps). Booster berlaku selama periode promo; setelahnya kembali ke kecepatan normal. Paket 20, 500, dan 1000 Mbps tanpa booster — speed penuh dari awal. Tanya masa berlaku booster terbaru ke sales.' },
  { q: 'Apakah internet XL SATU cocok untuk gaming online?', a: 'Sangat cocok! Jaringan fiber optik XL SATU memiliki latensi rendah yang ideal untuk gaming online. Untuk pengalaman gaming terbaik, kami merekomendasikan paket 250 Mbps ke atas. Paket 500 Mbps tersedia untuk cloud gaming dan gaming pro. Baca juga <a href="https://xlsatusolo.com/kecepatan-wifi-ideal-keluarga/">panduan kecepatan WiFi ideal untuk keluarga</a> dan <a href="https://xlsatusolo.com/berapa-mbps-untuk-berapa-orang/">panduan Mbps per jumlah orang</a> untuk rekomendasi lengkap sesuai kebutuhan rumah kamu.' },
  { q: 'Bagaimana jika internet saya bermasalah?', a: 'Anda bisa menghubungi layanan pelanggan XL SATU melalui WhatsApp Care di 08170010820, Call Center 820 (pengguna XL) atau 08170123442 (non-XL). Untuk bantuan teknis cepat di area Solo Raya, bisa juga hubungi sales kami langsung.' },
  { q: 'Apakah bisa pasang XL SATU untuk kos atau kontrakan di Solo?', a: 'Bisa! XL SATU cocok untuk kos, kontrakan, maupun rumah sendiri. Untuk kos dengan banyak penghuni, paket 400 Mbps atau 500 Mbps sangat direkomendasikan karena mendukung banyak perangkat secara bersamaan. Baca <a href="https://xlsatusolo.com/panduan-wifi-kos-solo/">panduan lengkap pilih WiFi kos di Solo Raya</a> untuk tips kecepatan dan cara patungan yang adil.' },
  { q: 'Berapa lama masa kontrak XL SATU?', a: 'Masa kontrak minimum XL SATU adalah 12 bulan. Jika Anda ingin berhenti berlangganan sebelum 12 bulan, wajib memberikan pemberitahuan minimal 14 hari sebelum pemutusan dan membayar biaya penalti sebesar Rp 1.000.000 serta melunasi semua tagihan yang belum dibayar.' },
  { q: 'Apa yang terjadi jika saya mau berhenti berlangganan?', a: 'Hubungi customer service XL SATU, siapkan KTP/Kartu Identitas Pelanggan, dan kembalikan perangkat (ONT/Modem) dalam kondisi lengkap. Pengembalian perangkat wajib dilakukan saat berakhirnya masa berlangganan atau pemutusan layanan.' },
  { q: 'Apakah perangkat XL SATU milik saya?', a: 'Tidak. ONT (modem), router, dan perangkat pendukung lainnya adalah milik XL yang dipinjamkan selama masa berlangganan. Anda wajib menjaga perangkat dalam kondisi baik dan mengembalikannya saat berhenti berlangganan. Jika perangkat hilang atau rusak karena kelalaian, Anda wajib mengganti biaya penggantian.' },
  { q: 'Siapa saja yang bisa berlangganan XL SATU?', a: 'XL SATU bisa dipasang untuk rumah, kos, kontrakan, maupun kantor. Yang diperlukan hanya KTP/SIM/KITAS yang valid dan alamat pemasangan di area jangkauan XL SATU. Untuk cek apakah alamat Anda sudah terjangkau, hubungi sales kami.' },
  { q: 'Apa itu FUP pada paket wireless?', a: 'FUP (Fair Usage Policy) hanya berlaku untuk paket wireless/FWA dengan batas penggunaan wajar 1 TB (1.024 GB) per periode tagihan. Jika sudah mencapai batas, XL berhak menyesuaikan kecepatan hingga periode berikutnya. Anda bisa beli paket booster via aplikasi myXL untuk menambah kuota. FUP tidak berlaku untuk paket fiber optik — fiber unlimited tanpa batas kuota.' },
  { q: 'Berapa nomor sales First Media Solo Raya?', a: 'First Media kini bagian dari XL Satu (XLSMART). Untuk pasang baru WiFi rumah First Media di Solo Raya, hubungi sales resmi XL Satu Solo Raya <strong>0877-7899-9141</strong> (wa.me/xlsatusolo). Sales Center Solo: (0271) 6776 222, WA Solo Raya: 0877-3721-0910, Call Center: 021 1500 595 — tetap aktif.' },
];
